### PR TITLE
Add node check

### PR DESCRIPTION
**Pull request by jzaefferer**
Fixes #7

Also a small readme update

### CODE REVIEW

**Review by Almouro — APPROVED** [review]
Great! Thanks for submitting this @jzaefferer ! 🙏

**Comment by Almouro** [comment]
Follow https://github.com/bitrise-io/bitrise-steplib/pull/3831 to check for integration into Bitrise

**Comment by bam-charlesbo** [comment]
@Almouro,
You're right this issue is a fix to #19 

Glad someone fixed it !

**Comment by jzaefferer** [comment]
And to https://github.com/Almouro/bitrise-nvm-step/issues/17 - I messed up the ticket reference in my original commit message. #7 has nothing to do with this.

**Pull request merged**
